### ISSUE TITLE
Imaginary drop

### ISSUE THREAD

**Issue by itamblyn** [jmcelve2/cheshire#4]
It probably makes sense to throw a warning or otherwise indicate to the user that the imaginary component of psi are dropped (you could even confirm the fact that they are zero before hand...)

**Comment by jmcelve2** [comment]
Do you mean E? I never explicitly pull out the real component of psi, only E.

**Comment by itamblyn** [comment]
Sorry, I misread your code. Yes, what you have looks correct.
