### ISSUE TITLE
Setting the real space lengths

### ISSUE THREAD

**Issue by kryczko** [jmcelve2/cheshire#8]
Along with the grid, we should set the size of the 'cell' we are working in. Since we are working in atomic units, the cell lengths would be in Bohr.

**Comment by jmcelve2** [comment]
Makes sense. I can address this in future pushes.

**Comment by jmcelve2** [comment]
I think this is already available in the Grid API. In addition to setting the number of cells with `n_x` and `n_y`, you can set the size of the grid with `x_min`, `x_max`, `y_min`, and `y_max`.
